// <auto-generated />
using System;
using AuditTrail.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditTrail.Domain.Migrations
{
    [DbContext(typeof(AuditTrailDataContext))]
    [Migration("20241114033706_InitAuditTrail")]
    partial class InitAuditTrail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-rc.1.24451.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditTrail.Domain.Models.AuditTrailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<int?>("EntityType")
                        .HasColumnType("integer");

                    b.Property<int?>("ExceptionType")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Uri")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("AuditTrail", "Logs");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("AuditTrail.Domain.Models.AuditTrailArchiveEntity", b =>
                {
                    b.HasBaseType("AuditTrail.Domain.Models.AuditTrailEntity");

                    b.Property<DateTime>("ArchiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("AuditTrailArchive", "Logs");
                });

            modelBuilder.Entity("AuditTrail.Domain.Models.AuditTrailArchiveEntity", b =>
                {
                    b.HasOne("AuditTrail.Domain.Models.AuditTrailEntity", null)
                        .WithOne()
                        .HasForeignKey("AuditTrail.Domain.Models.AuditTrailArchiveEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
